### ISSUE TITLE
very cool ui, but can you make a local folder settings, so we dont need to upload parquet files. when npm run start it can show visualizer

### ISSUE THREAD

**Issue by munger1985** [noworneverev/graphrag-visualizer#10]
very cool ui, but can you make a local folder settings, so we dont need to upload parquet files. when npm run start it can show visualizer

**Comment by noworneverev** [comment]
After #17, you can now place your Parquet files in the `public/artifacts` folder. The visualization will appear once you start the app. Please refer to the README for detailed instructions.
