### ISSUE TITLE
Local search fails sometimes

### ISSUE THREAD

**Issue by gmile** [noworneverev/graphrag-visualizer#12]
Sometimes, local search is failing with the following exception:

![CleanShot 2024-08-28 at 13 11 25@2x](https://github.com/user-attachments/assets/06f07786-323d-49c1-8449-fa744eed1409)

Sadly, I'm receiving this on error on a private data set that I am unable to attach here to help reproducing this...

**Comment by wanchichang** [comment]
same issue
