### ISSUE TITLE
Global & Local Search Not Working

### ISSUE THREAD

**Issue by BobbyAxelrods** [noworneverev/graphrag-visualizer#24]
Hi, 

Great repo. Seeking for further clarification on how to make the query works using this ? 

Thanks

**Comment by noworneverev** [comment]
Go to [graphrag-api](https://github.com/noworneverev/graphrag-api) and follow the instructions to start the local server.
Once the server is running, you can make a query by either cloning this project and running it locally or by using the query panel in the [graphrag-visualizer](https://noworneverev.github.io/graphrag-visualizer)
![image](https://github.com/user-attachments/assets/579b7a4e-d2ab-48f9-a048-2d32549f912d)
- Tick "Include Text Unit" and "Include Communities" to use Local Search
- Tick  "Include Communities" to use Global Search.

**Comment by BobbyAxelrods** [comment]
Thanks. Great response. 

1 last question is that, we im trying to deploy locally, im facing the error of node is missing. It seems backend are missing the node as shown below. Seek for your kind thought on this . 
![image (1)](https://github.com/user-attachments/assets/d9260ae0-ae59-46b5-856e-5ccc78153daf)


nonetheless, i fixed it by create main.css file and display it none and import this file in app.tsx 

`iframe
    {
        display: none;
    }`

The error still there but its not showing the popup anymore 
![image](https://github.com/user-attachments/assets/370bf394-b1b7-4667-9789-eafd3cc319df)

**Comment by noworneverev** [comment]
Thank you for reporting this issue. I’ve adapted both graphrag-api and graphrag-visualizer to the latest v1.0.0. Please try again, and feel free to reopen the issue if you encounter any further errors.
