### ISSUE TITLE
Lack of relationships in the graph

### ISSUE THREAD

**Issue by hanlv15** [noworneverev/graphrag-visualizer#25]
It seems that the relationship line from source to target cannot be seen in the graph.

**Comment by noworneverev** [comment]
> It seems that the relationship line from source to target cannot be seen in the graph.

Thank you for reporting this! The site has been updated to support GraphRAG v0.5.0 (#26) , which includes changes to the columns in the Parquet files. 

Please ensure your Parquet files are generated with graphrag **v0.5.0** to match the updated structure. For older versions (e.g., 0.3.x or 0.2.x), use the legacy site: [GraphRAG Visualizer Legacy](https://noworneverev.github.io/graphrag-visualizer-legacy).

Let me know if you still encounter issues!
