### ISSUE TITLE
Visualization not working

### ISSUE THREAD

**Issue by Adriansdls** [noworneverev/graphrag-visualizer#27]
I have been using this amazing repo for months. Suddenly nothing happens when i upload the parquet files. There is nothing in the data tables tab, or in the visualization tab. I think it has been going on for a couple of weeks. I have tried to generate the parquet files with several graoh-rag versions, but still nothing happens

**Comment by noworneverev** [comment]
Please refer to #25 

In short, if you use graphrag 0.5.0, it should work now. Otherwise use the legacy version: https://noworneverev.github.io/graphrag-visualizer-legacy/

**Comment by Adriansdls** [comment]
You're right @noworneverev , I should have realised, sorry about that. That said, legacy doesn't work in any browser. It just shows an empty white screen.

**Comment by noworneverev** [comment]
> You're right @noworneverev , I should have realised, sorry about that. That said, legacy doesn't work in any browser. It just shows an empty white screen.

Thank you for reporting. I've fixed the legacy site.
