### ISSUE TITLE
Legacy website is not loading

### ISSUE THREAD

**Issue by dipakmeher** [noworneverev/graphrag-visualizer#28]
Hi,

Thank you for modifying the project to handle the recent changes in the GraphRAG output files and for providing the link to the old legacy application. However, the legacy website is not loading. Could you please look into this issue?

Thanks!

**Comment by noworneverev** [comment]
> Hi,
> 
> Thank you for modifying the project to handle the recent changes in the GraphRAG output files and for providing the link to the old legacy application. However, the legacy website is not loading. Could you please look into this issue?
> 
> Thanks!

Thank you for reporting. I've fixed it.
