### ISSUE TITLE
Local Search not working

### ISSUE THREAD

**Issue by Adriansdls** [noworneverev/graphrag-visualizer#29]
This has been happening for weeks. I was never able to run a Local Search query in the visualiser tab. That said, the Global Search always works fine. I get Internal Server Error. This is with the Legacy version

INFO:     127.0.0.1:63137 - "GET /search/local?query=Do+I+have+a+honeymoon+permit%3F HTTP/1.1" 500 Internal Server Error

I think it might be related to graphrag and lancedb itself, and the vector column in the graphrag dataframes

**Comment by noworneverev** [comment]
> This has been happening for weeks. I was never able to run a Local Search query in the visualiser tab. That said, the Global Search always works fine. I get Internal Server Error. This is with the Legacy version
> 
> INFO: 127.0.0.1:63137 - "GET /search/local?query=Do+I+have+a+honeymoon+permit%3F HTTP/1.1" 500 Internal Server Error
> 
> I think it might be related to graphrag and lancedb itself, and the vector column in the graphrag dataframes

Thank you for reporting this issue. I’ve adapted both `graphrag-api` and `graphrag-visualizer` to the latest v1.0.0. Please try again, and feel free to reopen the issue if you encounter any further errors.
